
# Four taxa and two areas


Now, we load the data included in the package: tree and distribution.

```{r}


#data(package = "blepd")

## trees

data(tree)

str(tree)

initialTree <- tree


## distributions

data(distribution)

str(distribution)

dist4taxa <- distribution

## distribution to XY to be able to plot the data, otherwise skip the next step

distXY <- matrix2XY(dist4taxa)


## plotting

## the tree

plotTree <-  ggtree(initialTree, ladderize=TRUE,
                    color="black", size=1, linetype="dotted") +
             geom_tiplab(size=6, color="black") +
             theme_tree2() +
             ggtitle("Four terminals, equal branch length")


##print(plotTree)



## the distribution

plotDistrib <- ggplot(data=distXY,
                      aes(x= Area, y= Terminal),
                      size =11) +
               geom_point() +
               labs(title = "Distributions",
                    y = "",
                    x = "Area")

##print(plotDistrib)

cowplot::plot_grid(plotTree, plotDistrib, ncol=2)

```

We check whether names in both objects: initialTree and dist4taxa, are the same.

```{r}

all(colnames(dist4taxa) == initialTree$tip.label)

```

We report the branch length, and calculate the PD values.

```{r}

initialTree$edge.length

initialPD <- PDindex(tree=initialTree, distribution = dist4taxa)

initialPD

```

As expected there is a tie between both areas.




